name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "bye"
